In [4]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset 
import numpy as np
import pickle
import os
import json

In [5]:
dir = r"/Volumes/ESSD/BatteryLife"
content = os.listdir(dir)
print(f"###### \n ---- Raw Content ---- \n{content} \n######")
folders = [f for f in content if os.path.isdir(os.path.join(dir, f)) and (f != "Life labels" and f != "READMEs")]
print(f"###### \n ---- Battery Folders ---- \n{folders} \n######")

###### 
 ---- Raw Content ---- 
['CALB', 'CALCE', 'HNEI', 'HUST', 'ISU_ILCC', 'Life labels', 'MATR', 'MICH', 'MICH_EXP', 'NA-ion', 'README.md', 'READMEs', 'RWTH', 'SDU', 'SNL', 'Stanford', 'Stanford_2', 'Tongji', 'UL_PUR', 'XJTU', 'ZN-coin', '.DS_Store', '._.DS_Store', '._README.md'] 
######
###### 
 ---- Battery Folders ---- 
['CALB', 'CALCE', 'HNEI', 'HUST', 'ISU_ILCC', 'MATR', 'MICH', 'MICH_EXP', 'NA-ion', 'RWTH', 'SDU', 'SNL', 'Stanford', 'Stanford_2', 'Tongji', 'UL_PUR', 'XJTU', 'ZN-coin'] 
######


In [11]:
dir = r"/Volumes/ESSD/BatteryLife/"

def get_length(dir):
    content = os.listdir(dir)
    length = 0
    for f in content:
        if f.startswith("._") or f.startswith(".DS_Store"):
            continue
        with open(os.path.join(dir, f), 'r') as file:
            data = json.load(file)
            length += len(data)
    return length


        

In [73]:
content = os.listdir(dir)
print(f"###### \n ---- Content ---- \n{content} \n######")
folders = [f for f in content if os.path.isdir(os.path.join(dir, f)) and (f != "Life labels" and f != "READMEs") and not f.startswith("._") and not f.startswith(".DS_Store")]
pkl_files = [[] for _ in folders]
for i, folder in enumerate(folders) :
    folder_path = os.path.join(dir, folder)
    for file in os.listdir(folder_path):
        if file.endswith('.pkl'):
            pkl_files[i].append(file)
print(len(pkl_files))

###### 
 ---- Content ---- 
['CALB', 'CALCE', 'HNEI', 'HUST', 'ISU_ILCC', 'Life labels', 'MATR', 'MICH', 'MICH_EXP', 'NA-ion', 'README.md', 'READMEs', 'RWTH', 'SDU', 'SNL', 'Stanford', 'Stanford_2', 'Tongji', 'UL_PUR', 'XJTU', 'ZN-coin', '.DS_Store', '._.DS_Store', '._README.md'] 
######
18


In [14]:
labels = os.path.join(dir, "Life labels")
dict_labels = {}
content = os.listdir(labels)
length = 0
for f in content:
    if f.startswith("._") or f.startswith(".DS_Store"):
      continue
    with open(os.path.join(labels, f), 'r') as file:
            data = json.load(file)
            dict_labels.update(data)
print(len(dict_labels.keys()))
print(dict_labels['Stanford_Nova_Regular_100.pkl'])

  

1208
470


In [ ]:
data = {}
data1 = {'color': 'red', 'value': 1}
data_total = {}
for i in range(2):
    data_total[i] = data1.copy()

In [ ]:
get_length(dir)

In [ ]:
class BatteryLifeDataset(Dataset):
    def __init__(self, root_dir, transform=None, target_transform=None):
        self.root_dir = root_dir
        self.transform = transform
        self.target_transform = target_transform
    
    def __len__(self):
        json_path = os.path.join(self.root_dir, "Life labels")
        return get_length(json_path)
    
    def __getitem__(self, idx):
        with open(self.root_dir, 'rb') as file:
            data = pickle.load(file)


In [27]:
x= torch.linspace(0, 10, steps=5)
y = torch.sin(x)
print(y)
p = torch.tensor([1, 2, 3])
t = x.unsqueeze(-1).pow(p)
t

tensor([ 0.0000,  0.5985, -0.9589,  0.9380, -0.5440])


tensor([[   0.0000,    0.0000,    0.0000],
        [   2.5000,    6.2500,   15.6250],
        [   5.0000,   25.0000,  125.0000],
        [   7.5000,   56.2500,  421.8750],
        [  10.0000,  100.0000, 1000.0000]])

In [44]:
tensor_1 = torch.tensor([[[1,2,4,5],[3,4,5,5],[6,5,3,4]],[[1,2,4,3],[3,4,5,5],[6,5,3,3]]])
tensor_1.shape
tensor_2 = tensor_1.reshape(2,-1)
print(tensor_2)


tensor([[1, 2, 4, 5, 3, 4, 5, 5, 6, 5, 3, 4],
        [1, 2, 4, 3, 3, 4, 5, 5, 6, 5, 3, 3]])
