In [1]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}


In [1]:
import smbclient

In [ ]:
smbclient.register_session(r"192.168.1.201", username="media", password="media123")
lists = smbclient.listdir(r"\\192.168.1.201\Media\Movs\FYP\BatteryLife_Processed")

In [26]:
dirs = [x for x in lists if x != "README.md"]
dirs

['Tongji',
 '.gitattributes',
 'MICH_EXP',
 'NA-ion',
 'ISU_ILCC',
 '._.DS_Store',
 'HNEI',
 'CALCE',
 'ZN-coin',
 'Stanford_2',
 'UL_PUR',
 '.git',
 'SNL',
 '._README.md',
 'CALB',
 'Life labels',
 'RWTH',
 'Stanford_2_labels.json',
 '.DS_Store',
 'Stanford',
 'MICH',
 'MATR',
 'HUST',
 'READMEs',
 'SDU',
 'XJTU']

In [4]:
print(car.values())
type(car.values())

dict_values(['Ford', 'Mustang', 1964])


dict_values

In [5]:
import torch
import numpy as np

In [14]:
def info(tensor):
    if isinstance(tensor, torch.Tensor):
        print(f"Tensor Info: \n Shape: {tensor.shape} \n Dtype: {tensor.dtype} \n Device: {tensor.device} \n")
    else:
        print("Not a tensor")   

In [8]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Ones Tensor: \n {x_ones} \n")
print(f"Ones_like tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones_like tensor: 
 tensor([[0.7993, 0.7039],
        [0.6829, 0.3687]]) 



In [15]:
shape = (2,3,2)
rand_tens = torch.rand(shape)   
print(rand_tens)
info(rand_tens)

tensor([[[0.6390, 0.2165],
         [0.9356, 0.9918],
         [0.5801, 0.1354]],

        [[0.6425, 0.9955],
         [0.4911, 0.0936],
         [0.9949, 0.4951]]])
Tensor Info: 
 Shape: torch.Size([2, 3, 2]) 
 Dtype: torch.float32 
 Device: cpu 



In [ ]:
def well_hello():
    def another_func():
        print("Hello from another func!")
    return another_func

me = well_hello()
me()
torch.nn.Linear(in_features=5, out_features=3)

class me:
    def __init__(self, name: str, age: int):
        self.name = name
        self.age = age

    def __str__(self):
        return f"My name is {self.name} and I am {self.age} years old."
    
person = me("George", 21)

Hello from another func!


Linear(in_features=5, out_features=3, bias=True)