In [3]:
import torch
import numpy as np

In [6]:
def tensor_info(tensor : torch.Tensor):
    if isinstance(tensor, torch.Tensor):
        print(f"Tensor shape: {tensor.shape}")
        print(f"Tensor dtype: {tensor.dtype}")
        print(f"Tensor device: {tensor.device}")
    else:
        print("Input is not a torch.Tensor")

In [4]:
data = [[1,2,3], [4,5,6], [7,8,9]]
t_data = torch.tensor(data)
type(t_data)

torch.Tensor

In [147]:
shape = (2,4)
rand_tensor = torch.rand(shape)
print(rand_tensor)
tensor_info(rand_tensor)
if torch.accelerator.is_available():
    rand_tensor = rand_tensor.to(torch.accelerator.current_accelerator())
tensor_info(rand_tensor)

tensor([[0.3547, 0.8263, 0.5179, 0.0105],
        [0.5287, 0.5880, 0.4347, 0.1857]])
Tensor shape: torch.Size([2, 4])
Tensor dtype: torch.float32
Tensor device: cpu
Tensor shape: torch.Size([2, 4])
Tensor dtype: torch.float32
Tensor device: mps:0


In [152]:
indexing = torch.ones(5,2)
print(indexing[:1])
print(torch.cat([indexing, indexing], dim=1))

tensor([[1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [1]:
class Test_With:
    def __init__(self, name: str, value: int):
        self.name = name
        self.value = value
    def __enter__(self):
        print(f"Entering with: {self.name}")
        return self.value
    def __exit__(self, exc_type, exc_val, exc_tb):
        print(f"Exiting with: {self.name}")

with Test_With("Test1", 42) as val:
    print(f"Inside with block, value: {val}")



Entering with: Test1
Inside with block, value: 42
Exiting with: Test1


In [158]:
from PIL import Image
import torchvision.transforms as transforms
img = Image.open("../Matlab/Figures/LG_Sample_OCV.png")
myimg = transforms.ToTensor()(img)
tensor_info(myimg)

Tensor shape: torch.Size([3, 1154, 1763])
Tensor dtype: torch.float32
Tensor device: cpu
